# Generated by Django 4.0.4 on 2023-11-23 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taller',
            name='imagen',
            field=models.ImageField(null=True, upload_to='talleres'),
        ),
    ]
